apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: {{.Values.namespace.name}}
  labels:
    app: techtrends
spec:
  replicas: 3 # {{.Values.replicas}}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        image: {{.Values.repository.image.name}}:{{.Values.repository.image.tag}}
        imagePullPolicy: {{.Values.container.image.pullPolicy}}
        ports:
        - containerPort: {{.Values.container.port}}
        livenessProbe:
          httpGet:
            path: {{.Values.container.livenessProbe.path}}
            port: {{.Values.container.port}}
        readinessProbe:
          httpGet:
            path: {{.Values.container.readinessProbe.path}}
            port: {{.Values.container.port}}
        resources:
          limits:
            memory: {{.Values.resources.limits.memory}}
            cpu: {{.Values.resources.limits.cpu}}
          requests:
            memory: {{.Values.resources.requests.memory}}
            cpu: {{.Values.resources.requests.cpu}}
