apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox
spec:
  selector:
    app.kubernetes.io/name: techtrends
  ports:
    - protocol: TCP
      port: {{.Values.service.port}}
      targetPort: 3111